### ISSUE TITLE
[Pelvis Model Rendering] Load model file into the generator

### ISSUE THREAD

**Issue by jilei-hao** [jilei-hao/hubmap-penntmc-modeling#3]
# Background
### EPIC: Pelvis Model Rendering
The HuBMAP ovary model generator creates ovary models to be rendered by the web UI, based on user input parameters. To help UI users have a better sense of the location and orientation of the ovary, we want to add a pelvis model to the render scene as a reference. 

### Task: Load model file into the generator
Import the model into the ovary model generator. The imported format should be able to be added to the render scene of the generator, together with the ovary model.

# Requirements
Download the pelvis data from [here](https://hubmapconsortium.github.io/ccf/pages/ccf-3d-reference-library.html), and write code to read the model and add output polydata to the scene.

# Deliverables

- [x] Pelvis model downloaded
- [x] Read the model into the generator and add it to the scene
- [x] Run a test see if the model has been loaded correctly
