### ISSUE TITLE
[Name Displaying] Disassemble ovary model sections and save to a vtkRenderWindow

### ISSUE THREAD

**Issue by jilei-hao** [jilei-hao/hubmap-penntmc-modeling#4]
# Background
### EPIC: Name Displaying
An important proposed feature of the HuBMAP Web UI is displaying section names. User should be able to get the section name by pointing to a section (getting name by section), and has the section highlighted when pointing to the name of the section (getting section by name).
### Task: Disassemble ovary model sections and save to a vtkRenderWindow
To implement the name displaying feature, the generator has to be modified to generate models in a disassembled format. Currently after extracting level-set models, the generator merges them together into one mesh file. For this task, generator needs to be changed to keep the models in disassembled format, and be added into a vtkRenderWindow, which can then be used to be exported as a JSON scene. The JSON scene then can be used by the web component for the name displaying.

# Requirements
Remove the assembling logic that assembles the ovary model sections and add the sections to a vtkRenderWindow. 

# Deliverables
- [ ] Assembling logic removed
- [ ] Model sections added to vtkRenderWindow
- [ ] Run a test to check if the sections has been rendered correctly
